inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

AllCops:
 DisplayStyleGuide: true
 DisplayCopNames: true
 Exclude:
  - 'db/schema.rb'
  - 'vendor/**/*'
  - 'config/environments/*.rb'
  - 'bin/*'

Rails:
 Enabled: True

Metrics/BlockLength:
 Exclude:
  - 'spec/**/*.rb'
  - 'Guardfile'
  - 'vendor/bundle'

Metrics/LineLength:
  # This will disable the rule completely, regardless what other options you put
  Enabled: false
  # Change the default 80 chars limit value
  Max: 10000
  # If you want the rule only apply to a specific folder/file
  Include:
    - 'app/**/*'
  # If you want the rule not to apply to a specific folder/file
  Exclude:
    - 'db/schema.rb'